CREATE TABLE finances_spend_category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_finances_spend_category PRIMARY KEY (category_id)
);

CREATE TABLE finances_spend
(
    spend_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    amount       DECIMAL,
    due_date     date,
    category_id  BIGINT,
    description  VARCHAR(255),
    is_due       BOOLEAN                                 NOT NULL,
    is_paid      BOOLEAN                                 NOT NULL,
    is_recurring BOOLEAN                                 NOT NULL,
    status       VARCHAR(255),
    CONSTRAINT pk_finances_spend PRIMARY KEY (spend_id)
);

ALTER TABLE finances_spend
    ADD CONSTRAINT FK_FINANCES_SPEND_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES finances_spend_category (category_id);
