-- =====================================================
-- MIGRAÇÃO SIMPLES - APENAS O ESSENCIAL
-- =====================================================

-- Criar tabela de authorities dos usuários
CREATE TABLE tbl_user_authorities (
    user_id   INTEGER     NOT NULL,
    authority VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, authority),
    FOREIGN KEY (user_id) REFERENCES tbl_app_user (id) ON DELETE CASCADE,
    CHECK (authority IN ('USER', 'ADMIN', 'CHANGE_PASSWORD_PRIVILEGE'))
);

-- Criar índices
CREATE INDEX idx_user_authorities_user_id ON tbl_user_authorities (user_id);

-- Adicionar authority USER para todos os usuários existentes
INSERT INTO tbl_user_authorities (user_id, authority)
SELECT id, 'USER' FROM tbl_app_user;

-- Criar tabela de tokens de reset de senha
CREATE TABLE tbl_password_reset_token (
    reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reset_token    VARCHAR(255),
    user_id        INTEGER NOT NULL,
    expiry_date    TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (user_id) REFERENCES tbl_app_user (id) ON DELETE CASCADE
);

-- Criar índices para performance
CREATE INDEX idx_password_reset_token_user ON tbl_password_reset_token (user_id);
CREATE INDEX idx_password_reset_token_token ON tbl_password_reset_token (reset_token);
