version: '3.8'

services:
  app:
    image: redmater/financesk:0.0.2
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: ${PROFILE}
      FINANCESK_SSL_KEYSTORE_PASSWORD: ${FINANCESK_SSL_KEYSTORE_PASSWORD}
      FINANCESK_DB_URL: ${FINANCESK_DB_URL}
      FINANCESK_DB_PROD_URL: ${FINANCESK_DB_PROD_URL}
      FINANCESK_DB_USER: ${FINANCESK_DB_USER}
      FINANCESK_DB_PASS: ${FINANCESK_DB_PASS}
      SPRING_DATASOURCE_HIKARI_DATA-SOURCE-PROPERTIES_SSLMODE: verify-full
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/ubuntu/.postgresql:/etc/postgresql-ssl:ro,noexec
      - /etc/letsencrypt/live/financesk.ddns.net/:/etc/letsencrypt/live/financesk.ddns.net:ro
    networks:
      - financesk_network
networks:
    financesk_network:
      driver: bridge
