services:
  app:
    image: redmater/financesk:latest
    container_name: financesK-app
    environment:
      TZ: "America/Fortaleza"
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      APP_BASE_URL: ${APP_BASE_URL}

      # Email
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # JWT
      SECRET_KEY: ${SECRET_KEY}

      # Uploads
      APP_UPLOAD_DIR: /app/uploads
      APP_MAX_FILE_SIZE: 10MB
      APP_MAX_REQUEST_SIZE: 10MB

      JAVA_OPTS: >
        -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200 -Xss512k -XX:MaxMetaspaceSize=128m
        -XX:+ExitOnOutOfMemoryError
        -Dspring.jmx.enabled=false
        -Djava.security.egd=file:/dev/./urandom
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8

      # Hikari / JPA
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "60000"
      SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: "10000"
      SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: "false"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "8"
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "300000"
      SPRING_JPA_PROPERTIES_HIBERNATE_ENABLE_LAZY_LOAD_NO_TRANS: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE: "20"
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES: "true"
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "10MB"
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "10MB"

      # Logging reduzido
      LOGGING_LEVEL_COM_FINANCESK: "WARN"
      LOGGING_LEVEL_ORG_HIBERNATE: "ERROR"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "WARN"
      LOGGING_LEVEL_ORG_APACHE: "WARN"

      # Actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when_authorized"
      MANAGEMENT_HEALTH_DB_ENABLED: "true"

    ports:
      - "8282:8080"

    networks:
      - financesk-net

    volumes:
      - app_files:/app/uploads
      - app_logs:/app/logs

    restart: unless-stopped

    mem_limit: 1g
    cpus: 0.5

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 400s

volumes:
  app_files:
    driver: local
  app_logs:
    driver: local

networks:
  financesk-net:
    driver: bridge
