version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: financesK-postgres
    environment:
      POSTGRES_DB: financesk_db
      POSTGRES_USER: financesk_admin
      POSTGRES_PASSWORD: securePassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financesk_admin -d financesk_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financesK-app
    environment:
      PROFILE: dev
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/financesk_db
      SPRING_DATASOURCE_USERNAME: financesk_admin
      SPRING_DATASOURCE_PASSWORD: securePassword123!
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  microservices-network:
    driver: bridge
